[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "dsd2pcm-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.13.9"
dependencies = [
  "mutagen>=1.47.0",
  "numpy>=2.3.5",
  "pyside6>=6.10.1",
  "soundfile>=0.13.1",
  "threadpoolctl>=3.6.0",
]

[dependency-groups]
dev = [
  "cython>=3.2.1",
  "maturin>=1.10.2",
  "nuitka>=2.8.6",
  "ruff>=0.14.6",
  "setuptools>=80.9.0",
  "types-setuptools>=80.9.0.20250822",
]

[tool.ruff.lint]
extend-select = [
  "UP",
  "YTT",
  "ASYNC",
  "S",
  "B",
  "A",
  "COM",
  "C4",
  "ISC",
  "PIE",
  "PT",
  "ARG",
  "PTH",
  "NPY",
  "N",
  "RUF",
  "I",
]
ignore = ["RUF003", "RUF002", "S110", "N806", "COM812"]

[tool.ruff.format]
docstring-code-format = true
